package com.example.workoutplan;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WorkoutPlan {
    private String planId; // Will be auto-generated by Firestore
    private String userId;
    private String name;

    private List<WorkoutDay> days = new ArrayList<>();

    // Empty constructor for Firestore
    public WorkoutPlan() {}

    public WorkoutPlan(String userId, String name) {
        this.userId = userId;
        this.name = name;
    }

    // Getters and setters


    public String getPlanId() {
        return planId;
    }

    public void setPlanId(String planId) {
        this.planId = planId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<WorkoutDay> getDays() {
        return days;
    }

    public void setDays(List<WorkoutDay> days) {
        this.days = days;
    }
}